name: ci/cd

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

permissions:
  contents: read

jobs:
  build:
    name: Build containers
    permissions:
      contents: read # to fetch the repository content
      id-token: write # for signing attestation(s) with GitHub OIDC Token
    uses: docker/github-builder/.github/workflows/build.yml@v1
    with:
      output: local
      artifact-upload: true
      artifact-name: build-caddy-bin
      sign: false
      platforms: >-
        linux/amd64
        # linux/arm64/v8,
        # linux/arm/v7,
        # linux/arm/v6,
        # linux/ppc64le,
        # linux/riscv64,
        # linux/s390x
      file: caddy-plugins.Dockerfile
      build-args: |
        GO_IMAGE_VERSION=${{ vars.GO_IMAGE_VERSION }}
        XCADDY_VERSION=${{ vars.XCADDY_VERSION }}
        ALPINE_VERSION=${{ vars.ALPINE_VERSION }}
        CADDY_VERSION=${{ vars.CADDY_VERSION }}
        # CADDY_VERSION=${{ github.ref_name }}
        CADDY_CF_DNS_VERSION=${{ vars.CADDY_CF_DNS_VERSION }}

  release:
    needs: build
    if: github.ref_type == 'tag'
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write # for signing attestation(s) with GitHub OIDC Token
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v8
      with:
        path: artifacts
        name: build-caddy-bin
    - name: Rename binaries for release
      run: |
        ls -lh artifacts
        mv artifacts/linux_amd64/usr/bin/caddy caddy-plugins-bin_amd64-${{ github.ref_name }}
        mv artifacts/linux_arm64/usr/bin/caddy caddy-plugins-bin_arm64-${{ github.ref_name }}
        mv artifacts/linux_arm_v6/usr/bin/caddy caddy-plugins-bin_arm_v6-${{ github.ref_name }}
        mv artifacts/linux_arm_v7/usr/bin/caddy caddy-plugins-bin_arm_v7-${{ github.ref_name }}
        mv artifacts/linux_ppc64le/usr/bin/caddy caddy-plugins-bin_ppc64le-${{ github.ref_name }}
        mv artifacts/linux_riscv64/usr/bin/caddy caddy-plugins-bin_riscv64-${{ github.ref_name }}
        mv artifacts/linux_s390x/usr/bin/caddy caddy-plugins-bin_s390x-${{ github.ref_name }}
    - name: Release
      uses: softprops/action-gh-release@v3
      with:
        files: |
          caddy-plugins-bin*

