name: ci/cd

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

permissions:
  contents: read

jobs:
  build:
    name: Build containers
    permissions:
      contents: read # to fetch the repository content
      id-token: write # for signing attestation(s) with GitHub OIDC Token
    uses: docker/github-builder/.github/workflows/build.yml@v1
    with:
      output: local
      artifact-upload: true
      artifact-name: build-caddy-bin
      sign: false
      platforms: >-
        linux/amd64,
        linux/arm64/v8,
        linux/arm/v7,
        linux/arm/v6,
        linux/ppc64le,
        linux/riscv64,
        linux/s390x
      file: caddy-plugins.Dockerfile
      build-args: |
        GO_IMAGE_VERSION=${{ vars.GO_IMAGE_VERSION }}
        XCADDY_VERSION=${{ vars.XCADDY_VERSION }}
        ALPINE_VERSION=${{ vars.ALPINE_VERSION }}
        CADDY_VERSION=${{ vars.CADDY_VERSION }}
        # CADDY_VERSION=${{ github.ref_name }}
        CADDY_CF_DNS_VERSION=${{ vars.CADDY_CF_DNS_VERSION }}

  release:
    needs: build
    if: github.ref_type == 'tag'
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write # for signing attestation(s) with GitHub OIDC Token
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v8
      with:
        path: artifacts
        name: build-caddy-bin
    - name: Rename binaries for release
      run: |
        arr_folders=(artifacts/*)
        for i in "${arr_folders[@]}"
        do :
           MV_CMD="artifacts/$(echo $i | cut -c 11-)/usr/bin/caddy caddy-plugins-bin-$(echo $i | cut -c 11-)-${{ github.ref_name }}"
           mv ${MV_CMD}
        done
    - name: Release
      uses: softprops/action-gh-release@v3
      with:
        files: |
          caddy-plugins-bin*

